---
# Source: keep-alive/templates/config-map.yaml
apiVersion: v1
data:
  ENDPOINTS: https://weather.redkitedevelopment.co.uk
  NODE_ENV: production
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keep-alive
    helm.sh/chart: keep-alive-1.0.0
  name: keep-alive
---
# Source: keep-alive/templates/cron-job.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keep-alive
    helm.sh/chart: keep-alive-1.0.0
  name: keep-alive
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: keep-alive
            image: keep-alive
            imagePullPolicy: Always
            name: keep-alive
            resources:
              limits:
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 100Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
            volumeMounts:
            - mountPath: /tmp
              name: temp-dir
          restartPolicy: Never
          securityContext:
            fsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumes:
          - emptyDir: {}
            name: temp-dir
  schedule: 0/10 * * * *
  successfulJobsHistoryLimit: 1
