container:
  image: keep-alive
  resourceTier: S
  skipDefault: true

configMap:
  environment: production
  endpoints: https://weather.redkitedevelopment.co.uk

cronJob: 
  schedule: "0/10 * * * *"
  concurrencyPolicy: Forbid
  restartPolicy: Never
  successfulJobsHistoryLimit: 1
