environment: production
name: keep-alive
image: keep-alive

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  endpoints: https://weather.redkitedevelopment.co.uk

cronJob: 
  schedule: "0/10 * * * *"
  concurrencyPolicy: Forbid
  restartPolicy: Never
  successfulJobsHistoryLimit: 1

secret:
  type: Opaque
